Make coq-hott as a dependency using github repo commit
This was necessary, don't know why however, since if I tried to build it
locally, using ./coq-hott.opam as source, I met an error saying something like
```
    - theories/dune:7
    Hint: rm -f theories/Spaces/BAut/Bool/IncoherentIdempotent.glob
    Error: Multiple rules generated for
    _build/default/theories/Categories/Functor/Composition/Functorial/Attributes.glob:
    - file present in source tree
    - theories/dune:7
    Hint: rm -f
    theories/Categories/Functor/Composition/Functorial/Attributes.glob
    error: command failed: 'dune' 'build' '-p' 'coq-hott' '-j' '4' '@install' (exited with 1)
    esy-build-package: exiting with errors above...
```